version: "3.9"

services:
  search:
    image: "getmeili/meilisearch"
    container_name: "meteor__search"
    hostname: "search"
    volumes:
      - "meteor__search__volume:/meili_data"
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: "local_MEILI_KEY+123!"
  messaging:
    image: "rabbitmq:management"
    container_name: "meteor__messaging"
    hostname: "messaging"
    volumes:
      - "meteor__messaging__volume:/var/lib/rabbitmq"
    ports:
      - "5672:5672"
      - "8080:15672"
  postgres:
    image: "postgres:15-alpine"
    container_name: "meteor__postgres"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "core+ADMIN!123"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - "meteor__postgres__volume:/var/lib/postgresql/data"

volumes:
  meteor__search__volume:
    external: true
  meteor__postgres__volume:
    external: true
  meteor__messaging__volume:
    external: true
